#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -j y
#$ -o /usr4/bf527/lkzhang/joblogs
#$ -N tophat 
#$ -pe mpi_16_tasks_per_node 16

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

dir='/projectnb/bf528/users/lava-lamp/project-2-lava-lamp-1/samples'
read1=$dir/P0_1_1.fastq
read2=$dir/P0_1_2.fastq
bowtieindex='/project/bf528/project_2/reference/mm9'

#Load modules 
module load samtools bowtie2 boost python2 tophat

tophat -r 200 -G /project/bf528/project_2/reference/annot/mm9.gtf --segment-length=20 --segment-mismatches=1 --no-novel-juncs -o P0_1_tophat -p 16 $bowtieindex $read1 $read2

 
echo "Job finished: $(date +%F)"
